### ISSUE TITLE
how many tracking channel is supported?

### ISSUE THREAD

**Issue by iceberg1369** [noelpedro/WES_Capstone_GNSS_MR#1]
I would like to know how many tracking or acquisition channel is available?

**Comment by noelpedro** [comment]
Hi @iceberg1369 the number of tracking modules depends on the amount of resources available in the programming logic. In addition to this, there is only one acquisition accelerator, more can be also used depending on drivers on the PS. Also can you delete your fork of this repo and refork again? Please and thanks

**Comment by iceberg1369** [comment]
@noelpedro I understand that number of tracking channels limited by available resources. but I'm curious about current project setting and used board?

**Comment by noelpedro** [comment]
I did 24 total tracking correlators.
